// backend/routes/summaries.js - COMPLETE FIXED
const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const Summary = require('../models/Summary');
const fs = require('fs');
const path = require('path');

// ✅ GET ALL SUMMARIES
router.get('/', auth, async (req, res) => {
  try {
    const summaries = await Summary.find({ userId: req.user.id }).sort({ createdAt: -1 });
    res.json(summaries);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ GET SINGLE SUMMARY
router.get('/:id', auth, async (req, res) => {
  try {
    const summary = await Summary.findById(req.params.id);
    if (!summary) return res.status(404).json({ message: 'Not found' });
    if (summary.userId.toString() !== req.user.id) return res.status(401).json({ message: 'Not authorized' });
    res.json(summary);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ CREATE SUMMARY
router.post('/', auth, async (req, res) => {
  try {
    const summary = new Summary({
      ...req.body,
      userId: req.user.id
    });
    await summary.save();
    res.json(summary);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ UPDATE SUMMARY
router.put('/:id', auth, async (req, res) => {
  try {
    let summary = await Summary.findById(req.params.id);
    if (!summary) return res.status(404).json({ message: 'Not found' });
    if (summary.userId.toString() !== req.user.id) return res.status(401).json({ message: 'Not authorized' });

    summary = await Summary.findByIdAndUpdate(req.params.id, { $set: req.body }, { new: true });
    res.json(summary);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ DOWNLOAD AUDIO
router.get('/:id/download-audio', auth, async (req, res) => {
  try {
    const summary = await Summary.findById(req.params.id);
    if (!summary) return res.status(404).json({ message: 'Not found' });
    if (summary.userId.toString() !== req.user.id) return res.status(401).json({ message: 'Not authorized' });
    if (!summary.audioFilePath) return res.status(404).json({ message: 'No audio' });

    const filePath = path.join(__dirname, '..', 'audio_files', path.basename(summary.audioFilePath));
    if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'File not found' });

    const fileName = `${summary.meeting.replace(/[^a-z0-9]/gi, '_')}-recording.wav`;
    res.download(filePath, fileName);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ DOWNLOAD PDF
router.get('/:id/download-pdf', auth, async (req, res) => {
  try {
    const summary = await Summary.findById(req.params.id);
    if (!summary) return res.status(404).json({ message: 'Not found' });
    if (summary.userId.toString() !== req.user.id) return res.status(401).json({ message: 'Not authorized' });

    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument({ margin: 50 });

    const fileName = `${summary.meeting.replace(/[^a-z0-9]/gi, '_')}-report.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);

    doc.pipe(res);

    // Title
    doc.fontSize(24).fillColor('#2563eb').text('Meeting Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#6b7280').text('Generated by MeetMind', { align: 'center' });
    doc.moveDown(2);

    // Details
    doc.fontSize(14).fillColor('#000000').text('Meeting Details', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#374151')
      .text(`Title: ${summary.meeting}`)
      .text(`Date: ${summary.date}`)
      .text(`Duration: ${summary.duration}`);
    doc.moveDown(2);

    // Key Points
    if (summary.keyPoints && summary.keyPoints.length > 0) {
      doc.fontSize(14).fillColor('#000000').text('Key Points', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#374151');
      summary.keyPoints.forEach((point, i) => {
        doc.text(`${i + 1}. ${point}`, { indent: 20 });
      });
      doc.moveDown(1);
    }

    // Action Items
    if (summary.actionItemsList && summary.actionItemsList.length > 0) {
      doc.fontSize(14).fillColor('#000000').text('Action Items', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#374151');
      summary.actionItemsList.forEach((item, i) => {
        doc.text(`${i + 1}. ${item.item}`, { indent: 20 });
      });
    }

    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;